"""schema initial

Revision ID: a2ec84e2d9d6
Revises: 
Create Date: 2026-08-04 20:02:21.211741

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy.generics
from sqlalchemy.dialects import postgresql

revision: str = 'a2ec84e2d9d6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grille_decision',
    sa.Column('version_grille', sa.String(length=30), nullable=False),
    sa.Column('seuils', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pdo', sa.Float(), nullable=False),
    sa.Column('score_reference', sa.Float(), nullable=False),
    sa.Column('odds_reference', sa.Float(), nullable=False),
    sa.Column('date_activation', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('auteur', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('version_grille')
    )
    op.create_table('journal_audit',
    sa.Column('evenement_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('acteur_id', sa.String(length=100), nullable=False),
    sa.Column('objet', sa.String(length=200), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('adresse_ip', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('evenement_id')
    )
    op.create_index(op.f('ix_journal_audit_type'), 'journal_audit', ['type'], unique=False)
    op.create_table('modele',
    sa.Column('modele_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('chemin_artefact', sa.String(length=500), nullable=True),
    sa.Column('metriques', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('date_entrainement', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('modele_id')
    )
    op.create_table('utilisateur',
    sa.Column('identifiant', sa.String(length=50), nullable=False),
    sa.Column('nom_complet', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('agence_id', sa.String(length=20), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateur_email'), 'utilisateur', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateur_identifiant'), 'utilisateur', ['identifiant'], unique=True)
    op.create_table('access_token',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('token', sa.String(length=43), nullable=False),
    sa.Column('created_at', fastapi_users_db_sqlalchemy.generics.TIMESTAMPAware(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['utilisateur.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_access_token_created_at'), 'access_token', ['created_at'], unique=False)
    op.create_table('decision_scoring',
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('societaire_id', sa.String(length=50), nullable=False),
    sa.Column('agent_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('entree', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('features_utilisees', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('probabilite', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('tranche', sa.String(length=30), nullable=False),
    sa.Column('montant_recommande', sa.Integer(), nullable=False),
    sa.Column('mode_calcul', sa.String(length=20), nullable=False),
    sa.Column('decomposition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version_modele', sa.String(length=30), nullable=False),
    sa.Column('version_grille', sa.String(length=30), nullable=False),
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_decision_scoring_societaire_id'), 'decision_scoring', ['societaire_id'], unique=False)
    # ### end Alembic commands ###

    # decision_scoring est en insertion seule (une decision ne se modifie pas) : garde-fou
    # applique au niveau de la base, pas seulement par discipline applicative.
    op.execute("""
        CREATE FUNCTION empecher_modification_decision_scoring()
        RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'decision_scoring est en insertion seule : % interdit', TG_OP;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER decision_scoring_insertion_seule
        BEFORE UPDATE OR DELETE ON decision_scoring
        FOR EACH ROW EXECUTE FUNCTION empecher_modification_decision_scoring();
    """)

    # Grille et modele actifs par defaut, editables ensuite sans redeploiement (ecran de
    # parametrage de la grille). Valeurs de depart reprises du prototype de reference, pas
    # une verite figee.
    op.execute("""
        INSERT INTO grille_decision
            (version_grille, seuils, pdo, score_reference, odds_reference, auteur, active)
        VALUES (
            'v0.1',
            '{
                "marge": 0.15,
                "lgd": 0.75,
                "multiplicateur_accord": 0.6,
                "multiplicateur_vigilance": 1.0,
                "multiplicateur_examen": 1.6,
                "coefficient_progression": 1.5,
                "montant_plancher": 50000,
                "plafond_produit": 3000000,
                "plafond_primo_emprunteur": 150000,
                "modulation_base": 1.3,
                "modulation_pente": 2.0,
                "modulation_min": 0.4,
                "modulation_max": 1.2
            }'::jsonb,
            20, 600, 50, 'migration_initiale', true
        )
    """)
    op.execute("""
        INSERT INTO modele (modele_id, type, version, metriques, actif)
        VALUES ('modele_constant', 'socle', 'constant-0.1.0', '{}'::jsonb, true)
    """)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS decision_scoring_insertion_seule ON decision_scoring")
    op.execute("DROP FUNCTION IF EXISTS empecher_modification_decision_scoring()")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_scoring_societaire_id'), table_name='decision_scoring')
    op.drop_table('decision_scoring')
    op.drop_index(op.f('ix_access_token_created_at'), table_name='access_token')
    op.drop_table('access_token')
    op.drop_index(op.f('ix_utilisateur_identifiant'), table_name='utilisateur')
    op.drop_index(op.f('ix_utilisateur_email'), table_name='utilisateur')
    op.drop_table('utilisateur')
    op.drop_table('modele')
    op.drop_index(op.f('ix_journal_audit_type'), table_name='journal_audit')
    op.drop_table('journal_audit')
    op.drop_table('grille_decision')
    # ### end Alembic commands ###
